Repository EstherManrique/CDMX009-BurgerQueen, pull requests merged in 2020-07, with the labels that each got.

#19 Feature h u 1 page rest day menu dian
  package-lock.json
  package.json
  src/App.js
  src/assets/imgs/chess.jpg
  src/assets/imgs/cola.jpg
  src/assets/imgs/doble-burger.jpg
  src/assets/imgs/eggs.jpg
  src/assets/imgs/fries.jpg
  src/assets/imgs/onion-rings.jpg
  src/assets/imgs/simple-burger.jpg
  src/assets/imgs/water-bottle.jpeg
  src/components/InitWaiter/index.js
  src/components/InitWaiter/styles.module.css
  src/components/Products/Products.js
  src/components/RestDay/index.js
  src/components/RestDay/styles.module.css
  src/components/ReusableProducts/index.js
  src/components/ReusableProducts/style.css
Labels: Layout

#20 First commit trial for this brach
  src/components/BreakFast/index.js
Labels: Layout

#22 Feature h u 1 page rest day menu dian
  src/assets/imgs/skillet.png
  src/components/BackgLogin/index.js
  src/components/Boton/style.css
  src/components/Logo/Logo.js
  src/components/Logo/Logo.module.css
  src/components/Logo/TypesLogo.css
  src/components/Products/Products.js
  src/components/RestDay/index.js
  src/components/RestDay/styles.module.css
  src/components/ReusableProducts/index.js
  src/components/ReusableProducts/style.css
  src/components/ReusableTable/index.js
Labels: Layout

#23 H u 1 page breakfast menu esther
  src/assets/imgs/american-coffe.jpg
  src/assets/imgs/coffe-milk.jpg
  src/assets/imgs/orange-juice.jpg
  src/assets/imgs/sandwich.jpg
  src/assets/imgs/skillet.png
  src/components/BackgLogin/index.js
  src/components/Boton/style.css
  src/components/BreakFast/index.js
  src/components/BreakFast/styles.module.css
  src/components/Logo/Logo.js
  src/components/Logo/Logo.module.css
  src/components/Logo/TypesLogo.css
  src/components/Products/Products.js
  src/components/RestDay/index.js
  src/components/RestDay/styles.module.css
  src/components/ReusableProducts/index.js
  src/components/ReusableProducts/style.css
  src/components/ReusableTable/index.js
Labels: Layout

#25 Feature h u 1 page rest day menu dian
  package-lock.json
  package.json
  src/App.js
  src/assets/imgs/american-coffe.jpg
  src/assets/imgs/coffe-milk.jpg
  src/assets/imgs/fondo-sartennnnnnnn.png
  src/assets/imgs/orange-juice.jpg
  src/assets/imgs/pink-circle.png
  src/assets/imgs/sandwich.jpg
  src/assets/imgs/trash.png
  src/components/BreakFast/index.js
  src/components/BreakFast/styles.module.css
  src/components/DateTime/styles.module.css
  src/components/Logo/TypesLogo.css
  src/components/RestDay/index.js
  src/components/RestDay/styles.module.css
  src/components/ReusableTable/index.js
  src/components/ReusableTable/styles.module.css
  src/components/WaiterAccount/index.js
  src/components/WaiterAccount/styles.module.css
  src/components/WaiterRegister/index.js
Labels: Layout

#27 add canges in Waiter account about layout
  src/App.js
  src/assets/imgs/cuadrado-bordes.png
  src/assets/imgs/fondo-sartennnnnnnn.png
  src/assets/imgs/ketchup.png
  src/assets/imgs/kitchen-hat-chef.png
  src/assets/imgs/salsas.png
  src/components/Boton/style.css
  src/components/BreakFast/index.js
  src/components/BreakFast/styles.module.css
  src/components/Header/index.js
  src/components/Header/styles.module.css
  src/components/Kitchen/index.js
  src/components/Kitchen/styles.module.css
  src/components/RestDay/index.js
  src/components/RestDay/styles.module.css
  src/components/ReusableTable/styles.module.css
  src/components/WaiterAccount/index.js
  src/components/WaiterAccount/styles.module.css
Labels: Layout

#29 add props, useEstate, in InitWaiter Breackfast, RestDay and ReusableT…
  src/App.js
  src/components/BreakFast/index.js
  src/components/InitWaiter/index.js
  src/components/InitWaiter/styles.module.css
  src/components/RestDay/index.js
  src/components/ReusableTable/index.js
  src/components/ReusableTable/styles.module.css
Labels: Layout

#35 add changes in package.json homepage line and app.js i added HashRout…
  build/asset-manifest.json
  build/index.html
  build/precache-manifest.d521f16579268b2a74316b36cb2cdc18.js
  build/service-worker.js
  build/static/css/main.34fda329.chunk.css
  build/static/css/main.34fda329.chunk.css.map
  build/static/js/2.a7219aa5.chunk.js
  build/static/js/2.a7219aa5.chunk.js.LICENSE.txt
  build/static/js/2.a7219aa5.chunk.js.map
  build/static/js/main.a89a94c1.chunk.js
  build/static/js/main.a89a94c1.chunk.js.map
  build/static/js/runtime-main.745238b7.js
  build/static/js/runtime-main.745238b7.js.map
  package.json
  src/App.js
Labels: Layout

#38 Feature/esther hu 1 database fb
  build/index.html
  src/App.js
  src/assets/imgs/fondo-sarten.png
  src/assets/imgs/fondo-sartennnnnnnn.ai
  src/assets/imgs/fondo-sartennnnnnnn.png
  src/assets/imgs/message.txt
  src/components/BackgLogin/index.js
  src/components/BreakFast/index.js
  src/components/InitWaiter/index.js
  src/components/Kitchen/index.js
  src/components/Tables/TableWaiter.jsx
  src/components/Tables/styles.module.css
  src/components/WaiterAccount/index.js
  src/components/WaiterAccount/styles.module.css
  src/components/WaiterRegister/index.js
  src/components/WaiterRegister/styles.module.css
  src/firebase.js
Labels: Documentation, Functionality, Layout

#39 Hotfix/correction bugs layout
  src/components/Boton/style.css
  src/components/BreakFast/index.js
  src/components/DateTime/styles.module.css
  src/components/InitWaiter/index.js
  src/components/InitWaiter/styles.module.css
  src/components/Logo/Logo.module.css
  src/components/Logo/TypesLogo.css
Labels: bug

#40 Hotfix/correction bugs layout
  src/assets/imgs/fondo-sarten.png
  src/components/Boton/style.css
  src/components/BreakFast/index.js
  src/components/BreakFast/styles.module.css
  src/components/InitWaiter/index.js
  src/components/Kitchen/index.js
  src/components/Kitchen/styles.module.css
  src/components/Logo/Logo.js
  src/components/Logo/TypesLogo.css
  src/components/Products/Products.js
  src/components/RestDay/index.js
  src/components/RestDay/styles.module.css
  src/components/ReusableTable/index.js
  src/components/Tables/TableWaiter.jsx
  src/components/Tables/styles.module.css
  src/components/WaiterAccount/index.js
  src/components/WaiterAccount/styles.module.css
  src/components/WaiterRegister/index.js
Labels: bug

#42 Add KitchenTable
  src/App.js
  src/components/BackgLogin/index.js
  src/components/BreakFast/index.js
  src/components/InitWaiter/index.js
  src/components/KitchenRegister/index.js
  src/components/KitchenRegister/styles.module.css
  src/components/Tables/TableKitchen.jsx
Labels: Layout

#44 Feature/esther hu 1 database fb
  src/App.js
  src/components/Boton/Boton.js
  src/components/BreakFast/index.js
  src/components/DateTime/DateTables.js
  src/components/DateTime/styles.module.css
  src/components/InitWaiter/index.js
  src/components/InitWaiter/styles.module.css
  src/components/Tables/TableKitchen.jsx
  src/components/Tables/TableWaiter.jsx
  src/components/WaiterRegister/index.js
  src/components/WaiterRegister/styles.module.css
Labels: Layout

#54 add example changes
  src/App.js
  src/components/Example/index.js
  src/components/Example/styles.module.css
Labels: Functionality

#68 Feature/crud trials of concept dm
  src/App.js
  src/components/BreakFast/index.js
  src/components/BreakFast/styles.module.css
  src/components/ReusableTable/index.js
Labels: Documentation, Functionality

#72 Hotfix/correction bug styles components tables
  src/components/BreakFast/index.js
  src/components/BreakFast/styles.module.css
  src/components/ReusableTable/WaiterTable.js
  src/components/ReusableTable/kitchenTable.js
  src/components/ReusableTable/styles.module.css
  src/components/Tables/TableKitchen.jsx
  src/components/Tables/TableWaiter.jsx
  src/components/Tables/styles.module.css
Labels: Layout, bug
